[package]
name = "saori-interface-rs"
version = "1.0.0"
edition = "2021"
authors = [ "tukinami seika" ]
license = "MIT"
readme = "README.md"
description = "library for SAORI of Ukagaka."

[dependencies]
encoding = "0.2.33"